### ISSUE TITLE
Estado del TP

### ISSUE THREAD

**Issue by juanbono** [juanbono/subastas-iasc-2018#18]
Estado de cada uno de los puntos del TP

- [x] [Escenario 1: Adjudicación Simple](https://github.com/juanbono/subastas-iasc-2018/issues/13) 
- [x] [Escenario 2: Adjudicación con Competencia](https://github.com/juanbono/subastas-iasc-2018/issues/14) 
- [x] [Escenario 3: Cancelación de la Subasta](https://github.com/juanbono/subastas-iasc-2018/issues/15) 
- [x] [Escenario 4: Registración en tiempo real](https://github.com/juanbono/subastas-iasc-2018/issues/16) 
- [x] [Escenario 5: Subastas múltiples](https://github.com/juanbono/subastas-iasc-2018/issues/17) 
- [x] [Escenario 6: Caída del servidor](https://github.com/juanbono/subastas-iasc-2018/issues/19) 
- [x] [Escenario 7: Falta de memoria en el servidor](https://github.com/juanbono/subastas-iasc-2018/issues/20)
